# SPDX-License-Identifier: CC0-1.0
# SPDX-FileCopyrightText: 2021-2022 The Foundation for Public Code <info@publiccode.net>, https://standard.publiccode.net/AUTHORS

name: release-on-tag
on:
  push:
    tags:
      - "*.*.*" # tag example: 0.4.1

defaults:
  run:
    shell: bash

jobs:
  release-the-tag:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: install-deps
        # https://yaml.org/spec/1.2.2/#65-line-folding
        run: >
          sudo apt-get install -y
          make
          docbook-utils
          pandoc
          inkscape
          texlive
          texlive-fonts-extra
          texlive-extra-utils
          fontconfig
      - name: install-fonts
        run: script/ensure-font.sh
      - name: make-release
        run: make release
      - name: create-release-body
        run: script/release-body.sh
      - name: upload
        uses: softprops/action-gh-release@v1
        with:
          prerelease: false
          files: |
            governance-game-*.tar.xz
            governance-game-box-*.pdf
            governance-game-*.zip
          body_path: release.body
